### ISSUE TITLE
Problème bateau

### ISSUE THREAD

**Issue by alexis-leclerc-uni** [alexis-leclerc-uni/BattleshipCLI#5]
Si le bateau est touché une fois, celui-ci est considéré comme étant coulé, ce qui n'est pas le comportement du jeu attendu. Par exemple, si je tire de 0 à 8 en y, avec un bateau placé à x 0 et y 0, voici le résultat. Pourtant, je n'ai pas tiré qu'une seule fois sur le bateau.

![image](https://github.com/alexis-leclerc-uni/BattleshipCLI/assets/146358811/bfde83b4-a660-4605-b6a1-6f857665230e)

Merci pour votre attention

**Comment by Douglass-McMuffin** [comment]
<img width="452" alt="image" src="https://github.com/alexis-leclerc-uni/BattleshipCLI/assets/147094989/32d83c8f-0e21-4989-9857-11c87cd580ea">
Ben non, les deux bateaux ont la variable false pour coule

**Comment by alexis-leclerc-uni** [comment]
oke goude

**Comment by alexis-leclerc-uni** [comment]
c'est bin bon
